2022-04-12 16:04:31,995 INFO  ==============================================================
2022-04-12 16:04:31,996 INFO  Id:    monitoring_with_simulated_messages
2022-04-12 16:04:31,997 INFO  Dir:   monitoring/
2022-04-12 16:04:31,998 INFO  Title: Validate the tedge dm agent messages that are produced from the simulated collectd messages
2022-04-12 16:04:31,999 INFO  ==============================================================
2022-04-12 16:04:32,570 INFO  Executed sudo<collectd>, exit status 0
2022-04-12 16:04:33,183 INFO  Executed sudo<collectd_mapper>, exit status 0
2022-04-12 16:04:33,193 INFO  Started sudo<tedge_sub> with process id 25251
2022-04-12 16:04:33,809 INFO  Executed sudo<tedge_temp>, exit status 0
2022-04-12 16:04:34,322 INFO  Executed sudo<tedge_pres>, exit status 0
2022-04-12 16:04:35,835 INFO  Executed sudo<kill_out>, exit status 0
2022-04-12 16:04:35,839 INFO  0

2022-04-12 16:04:35,840 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 98, in validate
    collectd_msg_validation_result=self.validate_json(),
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 108, in validate_json
    if not self.validate_time():
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 127, in validate_time
    if self.js_msg["time"]:
TypeError: 'int' object is not subscriptable
2022-04-12 16:04:35,855 WARN  TypeError: 'int' object is not subscriptable ... blocked 
2022-04-12 16:04:35,857 INFO  
2022-04-12 16:04:35,858 INFO  cleanup:
2022-04-12 16:04:35,858 INFO  monitoring_cleanup
2022-04-12 16:04:36,471 INFO  Executed sudo<collectd_mapper>, exit status 0
2022-04-12 16:04:36,475 INFO  
2022-04-12 16:04:36,476 INFO  Test duration: 4.48 secs
2022-04-12 16:04:36,477 INFO  Test final outcome:  BLOCKED
2022-04-12 16:04:36,478 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
2022-04-12 16:04:36,479 INFO  
