<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="apt_fail_noarg" skipped="0" tests="1" time="1.06" timestamp="2022-03-04T12:58:08">
	<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg">
		<failure message="BLOCKED: sudo&lt;outp_install&gt; returned exit code 2 (expected ==1)" type="BLOCKED"/>
		<system-out>12:58:06 INFO  ==============================================================
12:58:06 INFO  Id:    apt_fail_noarg
12:58:06 INFO  Dir:   plugin_apt/
12:58:06 INFO  Title: Validate apt plugin fetures(prepare, list, install, remove finalize) without arguments
12:58:06 DEBUG Execution order hint: 0.0
12:58:06 INFO  ==============================================================
12:58:07 DEBUG --- test execute
12:58:07 DEBUG Process parameters for sudo&lt;outp_install&gt;
  command line : /usr/bin/sudo /etc/tedge/sm-plugins/apt install
    arg #1     : /etc/tedge/sm-plugins/apt
    arg #2     : install
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_fail_noarg/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_fail_noarg/Output/linux/outp_install.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_fail_noarg/Output/linux/outp_install.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
12:58:07 DEBUG Waiting up to 600 secs for process sudo&lt;outp_install&gt; (pid 25102)
12:58:07 WARN  Executed sudo&lt;outp_install&gt;, exit status 2
12:58:07 DEBUG Opening file using encoding=UTF-8: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_fail_noarg/Output/linux/outp_install.err
12:58:07 INFO  Contents of outp_install.err: 
12:58:07 INFO    error: The following required arguments were not provided:
12:58:07 INFO        &lt;MODULE&gt;
12:58:07 INFO    USAGE:
12:58:07 INFO        apt install [OPTIONS] &lt;MODULE&gt;
12:58:07 INFO    For more information try --help
12:58:07 INFO    -----
12:58:07 INFO  
12:58:08 WARN  sudo&lt;outp_install&gt; returned exit code 2 (expected ==1) ... blocked [environment_apt_plugin.py:70,run.py:20]
12:58:08 WARN  Aborted test due to BLOCKED outcome
12:58:08 DEBUG --- test cleanup
12:58:08 DEBUG ProcessUser cleanup function done.
12:58:08 INFO  
12:58:08 INFO  Test duration: 1.06 secs
12:58:08 INFO  Test final outcome:  BLOCKED
12:58:08 INFO  Test outcome reason: sudo&lt;outp_install&gt; returned exit code 2 (expected ==1)
12:58:08 INFO  
</system-out>
	</testcase>
</testsuite>
