2022-04-14 10:22:08,057 INFO  ==============================================================
2022-04-14 10:22:08,058 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
2022-04-14 10:22:08,059 INFO  Dir:   software_management_end_to_end/
2022-04-14 10:22:08,060 INFO  Title: Install package to directory specified in tedge config set tmp.path
2022-04-14 10:22:08,061 INFO  ==============================================================
2022-04-14 10:22:08,429 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
2022-04-14 10:22:08,430 INFO  EnvironmentC8y Setup
2022-04-14 10:22:09,802 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-04-14 10:22:24,365 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 14 secs
2022-04-14 10:22:26,284 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-04-14 10:22:28,403 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-04-14 10:22:28,919 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-04-14 10:22:31,171 ERROR No operations found, assuming it passed
2022-04-14 10:22:31,383 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
2022-04-14 10:22:31,982 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
2022-04-14 10:22:31,983 INFO  
2022-04-14 10:22:31,984 INFO  cleanup:
2022-04-14 10:22:32,495 INFO  Executed sudo, exit status 0
2022-04-14 10:22:33,007 INFO  Executed sudo, exit status 0
2022-04-14 10:22:37,181 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-14 10:22:37,292 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
2022-04-14 10:22:37,293 INFO  Delaying execution by 8 seconds
2022-04-14 10:22:59,612 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 14 secs
2022-04-14 10:23:03,769 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-14 10:23:04,434 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-04-14 10:23:04,438 INFO  
2022-04-14 10:23:04,439 INFO  Test duration: 56.39 secs
2022-04-14 10:23:04,441 INFO  Test final outcome:  BLOCKED
2022-04-14 10:23:04,443 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
2022-04-14 10:23:04,445 INFO  
