2022-03-02 10:05:55,618 INFO  ==============================================================
2022-03-02 10:05:55,618 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
2022-03-02 10:05:55,619 INFO  Dir:   software_management_end_to_end/
2022-03-02 10:05:55,620 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
2022-03-02 10:05:55,620 DEBUG Execution order hint: 0.0
2022-03-02 10:05:55,620 INFO  ==============================================================
2022-03-02 10:05:55,625 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
2022-03-02 10:05:55,625 DEBUG EnvironmentC8y Setup
2022-03-02 10:05:55,626 INFO  EnvironmentC8y Setup
2022-03-02 10:05:55,627 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:05:55,631 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 13487)
2022-03-02 10:05:55,835 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-03-02 10:05:55,887 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
2022-03-02 10:05:55,888 INFO  Delaying execution by 9 seconds
2022-03-02 10:06:04,899 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:04,908 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 13492)
2022-03-02 10:06:14,864 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-03-02 10:06:14,865 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:14,870 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 13607)
2022-03-02 10:06:15,125 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-03-02 10:06:15,126 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:15,131 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 13609)
2022-03-02 10:06:15,336 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-03-02 10:06:15,337 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:15,343 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 13610)
2022-03-02 10:06:15,548 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-03-02 10:06:17,682 DEBUG Final URL of the request: https://thin-edge-io.eu-latest.cumulocity.com/devicecontrol/operations?deviceId=14890101&pageSize=1&revert=true&dateFrom=1970-01-01T00%3A00%3A00.000Z
2022-03-02 10:06:17,684 INFO  State of current operation: FAILED
2022-03-02 10:06:17,685 DEBUG Final URL of the request: https://thin-edge-io.eu-latest.cumulocity.com/devicecontrol/operations?deviceId=14890101&pageSize=1&revert=true&dateFrom=1970-01-01T00%3A00%3A00.000Z
2022-03-02 10:06:17,685 DEBUG State of current operation: {
    "delivery": {
        "time": "2022-03-02T09:04:44.105Z",
        "log": [
            {
                "time": "2022-03-02T09:04:44.068Z",
                "status": "PENDING"
            },
            {
                "time": "2022-03-02T09:04:44.076Z",
                "status": "SEND"
            }
        ],
        "status": "DELIVERED"
    },
    "creationTime": "2022-03-02T09:04:44.046Z",
    "deviceId": "14890101",
    "deviceName": "octocatrpi3",
    "failureReason": "1 error, see device log file /var/log/tedge/agent/software-update-2022-03-02T09:04:45.536115885Z.log",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/14902660",
    "id": "14902660",
    "status": "FAILED",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
2022-03-02 10:06:17,841 WARN  caught <class 'TypeError'> while running test: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1207, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 55, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 395, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
2022-03-02 10:06:17,852 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
2022-03-02 10:06:17,853 DEBUG --- test cleanup
2022-03-02 10:06:17,854 INFO  
2022-03-02 10:06:17,854 INFO  cleanup:
2022-03-02 10:06:17,855 DEBUG Running registered cleanup function: <bound method SoftwareManagement.mysmcleanup of <PySysTest object at 0x75234cb0>>
2022-03-02 10:06:17,855 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <PySysTest object at 0x75234cb0>>
2022-03-02 10:06:17,856 DEBUG EnvironmentC8y Cleanup
2022-03-02 10:06:17,931 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:17,937 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 13627)
2022-03-02 10:06:19,850 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-03-02 10:06:19,851 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 10:06:19,856 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 13667)
2022-03-02 10:06:20,059 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-03-02 10:06:20,060 DEBUG ProcessUser cleanup function done.
2022-03-02 10:06:20,061 INFO  
2022-03-02 10:06:20,062 INFO  Test duration: 24.44 secs
2022-03-02 10:06:20,062 INFO  Test final outcome:  BLOCKED
2022-03-02 10:06:20,063 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
2022-03-02 10:06:20,063 INFO  
