<?xml version="1.0" encoding="utf-8"?>
<testsuite name="docker_plugin_update" tests="1" failures="1" skipped="0" time="5.21" timestamp="2022-05-02T16:06:43">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>16:06:38 INFO  ==============================================================
16:06:38 INFO  Id:    docker_plugin_update
16:06:38 INFO  Dir:   plugin_docker/
16:06:38 INFO  Title: Validate docker plugin install updates existing containers
16:06:38 INFO  ==============================================================
16:06:38 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
16:06:38 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
16:06:41 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
16:06:41 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.6.2' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

16:06:41 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
16:06:41 WARN  Aborted test due to BLOCKED outcome
16:06:41 INFO  
16:06:41 INFO  cleanup:
16:06:41 INFO  Removing containers scheduled to be cleaned up: ['', '']
16:06:42 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
16:06:42 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1']
16:06:43 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
16:06:43 INFO  
16:06:43 INFO  Test duration: 5.21 secs
16:06:43 INFO  Test final outcome:  BLOCKED
16:06:43 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
16:06:43 INFO  
</system-out>
	</testcase>
</testsuite>
