2022-03-02 09:13:20,518 INFO  ==============================================================
2022-03-02 09:13:20,519 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
2022-03-02 09:13:20,520 INFO  Dir:   software_management_end_to_end/
2022-03-02 09:13:20,520 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
2022-03-02 09:13:20,521 DEBUG Execution order hint: 0.0
2022-03-02 09:13:20,521 INFO  ==============================================================
2022-03-02 09:13:20,527 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
2022-03-02 09:13:20,527 DEBUG EnvironmentC8y Setup
2022-03-02 09:13:20,528 INFO  EnvironmentC8y Setup
2022-03-02 09:13:20,529 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:20,534 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 23717)
2022-03-02 09:13:20,839 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-03-02 09:13:20,924 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
2022-03-02 09:13:20,925 INFO  Delaying execution by 9 seconds
2022-03-02 09:13:29,938 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:29,945 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 23721)
2022-03-02 09:13:40,226 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-03-02 09:13:40,230 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:40,237 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 23830)
2022-03-02 09:13:40,593 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-03-02 09:13:40,594 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:40,599 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 23834)
2022-03-02 09:13:40,853 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-03-02 09:13:40,855 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:40,860 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 23835)
2022-03-02 09:13:41,115 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-03-02 09:13:43,285 DEBUG Final URL of the request: https://thin-edge-io.eu-latest.cumulocity.com/devicecontrol/operations?deviceId=14879013&pageSize=1&revert=true&dateFrom=1970-01-01T00%3A00%3A00.000Z
2022-03-02 09:13:43,288 INFO  State of current operation: FAILED
2022-03-02 09:13:43,289 DEBUG Final URL of the request: https://thin-edge-io.eu-latest.cumulocity.com/devicecontrol/operations?deviceId=14879013&pageSize=1&revert=true&dateFrom=1970-01-01T00%3A00%3A00.000Z
2022-03-02 09:13:43,290 DEBUG State of current operation: {
    "delivery": {
        "time": "2022-03-02T09:12:00.117Z",
        "log": [
            {
                "time": "2022-03-02T09:12:00.072Z",
                "status": "PENDING"
            },
            {
                "time": "2022-03-02T09:12:00.080Z",
                "status": "SEND"
            }
        ],
        "status": "DELIVERED"
    },
    "creationTime": "2022-03-02T09:12:00.047Z",
    "deviceId": "14879013",
    "deviceName": "offsited",
    "failureReason": "1 error, see device log file /var/log/tedge/agent/software-update-2022-03-02T09:12:02.000354016Z.log",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/14902684",
    "id": "14902684",
    "status": "FAILED",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
2022-03-02 09:13:43,438 WARN  caught <class 'TypeError'> while running test: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1207, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 55, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 395, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
2022-03-02 09:13:43,475 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
2022-03-02 09:13:43,476 DEBUG --- test cleanup
2022-03-02 09:13:43,476 INFO  
2022-03-02 09:13:43,477 INFO  cleanup:
2022-03-02 09:13:43,477 DEBUG Running registered cleanup function: <bound method SoftwareManagement.mysmcleanup of <PySysTest object at 0x75d64510>>
2022-03-02 09:13:43,478 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <PySysTest object at 0x75d64510>>
2022-03-02 09:13:43,478 DEBUG EnvironmentC8y Cleanup
2022-03-02 09:13:43,583 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:43,589 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 23855)
2022-03-02 09:13:45,811 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-03-02 09:13:45,812 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 09:13:45,818 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 23895)
2022-03-02 09:13:46,123 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-03-02 09:13:46,124 DEBUG ProcessUser cleanup function done.
2022-03-02 09:13:46,126 INFO  
2022-03-02 09:13:46,127 INFO  Test duration: 25.61 secs
2022-03-02 09:13:46,128 INFO  Test final outcome:  BLOCKED
2022-03-02 09:13:46,128 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
2022-03-02 09:13:46,129 INFO  
